CREATE DATABASE TODOLIST;

CREATE TABLE TODO(
	id SERIAL PRIMARY KEY, title VARCHAR(100),
	description VARCHAR(255), time_created TIMESTAMP DEFAULT NOW(), time_due TIMESTAMP,
	completed boolean DEFAULT false
);
